spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: YOUR_PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSqlDialect
  flyway:
    enabled: true
    location: classpath:db/migration
  jwt:
    secret: YOUR_SECRET_KEY
    accessTokenExpiration: 72000
    refreshTokenExpiration: 604800
server:
  port: 8081
logging:
  level:
    org:
      springframework:
        security: DEBUG
bootstrap:
  admin:
    enabled: true
    adminName: super
    adminPassword: superadmin
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
